name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          APP_ID: ${{ SECRETS.APP_ID }} 
          TENANT_ID: ${{ SECRETS.TENANT_ID }}
          APP_SECRET: ${{ SECRETS.APP_SECRET }}
          SITE_ID: ${{ SECRETS.SITE_ID }}
          LIST_ID: ${{ SECRETS.LIST_ID }}

        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: jublaost.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t jublaost.azurecr.io/node-linkshortener:${{ github.sha }}
            docker push jublaost.azurecr.io/node-linkshortener:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}

        - run: |
            az account set --subscription ${{ SECRETS.SUBSCRIPTION_ID }}
            az container create --resource-group link-shortener --file deployment/deploy-aci.yaml